version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    image: node
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
  mariadb:
    image: mariadb:latest
    container_name: docker-mariadb
    # network_mode: "host"
    ports: 
      - "3306:3306"
    restart: always
    environment:
      - "MARIADB_ROOT_PASSWORD=asjdfpoiajsdadsfipjoiasjdf"
    volumes:  
      - dbdata:/data/db   
    networks:
      - app-network 
networks:
    app-network:
        driver: bridge
    
volumes:
    dbdata:
    node_modules:
